version: '3'

networks:
  student-exam-management-network:

services:
  # mysql
  mysql8-service:
    image: mysql:8
    container_name: mysql8-container
    ports:
      - "5306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    networks:
      - student-exam-management-network
  rabbitmq-service:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
      - student-exam-management-network
  mailhog-service:
    image: mailhog/mailhog
    container_name: mailhog-container
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - student-exam-management-network

  #User service
  # nginx
  user-nginx-service:
    image: nginx:stable-alpine
    container_name: user-nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./user-service/app:/var/www/project
      - ./user-service/nginx/default.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ./user-service/app/.env.local
    depends_on:
      - user-php83-service
    networks:
      - student-exam-management-network

  # php
  user-php83-service:
    build:
      context: .
      dockerfile: ./user-service/php/Dockerfile
    container_name: user-php83-container
    volumes:
      - ./user-service/app:/var/www/project
    networks:
      - student-exam-management-network
  # Exam service
  # nginx
  exam-nginx-service:
    image: nginx:stable-alpine
    container_name: exam-nginx-container
    ports:
      - "8081:80"
    volumes:
      - ./exam-service/app:/var/www/project
      - ./exam-service/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - exam-php83-service
    networks:
      - student-exam-management-network

  # php
  exam-php83-service:
    build:
      context: .
      dockerfile: ./exam-service/php/Dockerfile
    container_name: exam-php83-container
    volumes:
      - ./exam-service/app:/var/www/project
    networks:
      - student-exam-management-network

  # Class service
  # nginx
  class-nginx-service:
    image: nginx:stable-alpine
    container_name: class-nginx-container
    ports:
      - "8082:80"
    volumes:
      - ./class-service/app:/var/www/project
      - ./class-service/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - class-php83-service
    networks:
      - student-exam-management-network

  # php
  class-php83-service:
    build:
      context: .
      dockerfile: ./class-service/php/Dockerfile
    container_name: class-php83-container
    volumes:
      - ./class-service/app:/var/www/project
    networks:
      - student-exam-management-network

  # Transaction service
  # nginx
  transaction-nginx-service:
    image: nginx:stable-alpine
    container_name: transaction-nginx-container
    ports:
      - "8083:80"
    volumes:
      - ./transaction-service/app:/var/www/project
      - ./transaction-service/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - transaction-php83-service
    networks:
      - student-exam-management-network

  #  php
  transaction-php83-service:
    build:
      context: .
      dockerfile: ./transaction-service/php/Dockerfile
    container_name: transaction-php83-container
    volumes:
      - ./transaction-service/app:/var/www/project
    networks:
      - student-exam-management-network

  # Email service
  # nginx
  email-nginx-service:
    image: nginx:stable-alpine
    container_name: email-nginx-container
    ports:
      - "8084:80"
    volumes:
      - ./email-service/app:/var/www/project
      - ./email-service/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - email-php83-service
    networks:
      - student-exam-management-network

  #  php
  email-php83-service:
    build:
      context: .
      dockerfile: ./email-service/php/Dockerfile
    container_name: email-php83-container
    volumes:
      - ./email-service/app:/var/www/project
    networks:
      - student-exam-management-network

  # Email service
  # nginx
  exam-registration-service-nginx-service:
    image: nginx:stable-alpine
    container_name: exam-registration-nginx-container
    ports:
      - "8085:80"
    volumes:
      - ./exam-registration-service/app:/var/www/project
      - ./exam-registration-service/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - exam-registration-php83-service
    networks:
      - student-exam-management-network

  #  php
  exam-registration-php83-service:
    build:
      context: .
      dockerfile: ./exam-registration-service/php/Dockerfile
    container_name: exam-registration-php83-container
    volumes:
      - ./exam-registration-service/app:/var/www/project
    networks:
      - student-exam-management-network
