framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            user_updated_transport:
                serializer: messenger.transport.symfony_serializer
                dsn: '%env(USER_UPDATED_TRANSPORT_DSN)%'
                options:
                    auto_setup: false
                    exchange:
                        name: user-updated
                        type: direct
                        default_publish_routing_key: user-updated
                    queues:
                        user-updated:
                            binding_keys: [ 'user-updated' ]

        routing:
            'App\Message\UserUpdatedMessage': user_updated_transport


# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
