framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            student_update:
                serializer:  messenger.transport.symfony_serializer
                dsn: '%env(STUDENT_BUS_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: student_update
                        type: fanout
                    queues:
                        student_update: ~
                        student_update_email: ~


        routing:
            'App\Message\StudentUpdateMessage': student_update

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
