framework:
    messenger:
        transports:
            user_class_verification_transport:
                serializer: messenger.transport.symfony_serializer
                dsn: '%env(USER_CLASS_VERIFICATION_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: user-class-verification
                        type: direct
                        default_publish_routing_key: user-class-verification
                    queues:
                        user-class-verification:
                            binding_keys: ['user-class-verification']

        routing:
            'App\Message\UserClassVerificationMessage': user_class_verification_transport
