framework:
    messenger:
        transports:
            response_saga_item_transport:
                serializer: messenger.transport.symfony_serializer
                dsn: '%env(RESPONSE_SAGA_ITEM_TRANSPORT_DSN)%'
                options:
                    auto_setup: false
                    exchange:
                        name: response-saga-item
                        type: direct
                        default_publish_routing_key: response-saga-item
                    queues:
                        response-saga-item:
                            binding_keys: [ 'response-saga-item' ]
            user_class_verification_transport:
                serializer: messenger.transport.symfony_serializer
                dsn: '%env(USER_CLASS_VERIFICATION_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: user-class-verification
                        type: direct
                        default_publish_routing_key: user-class-verification
                    queues:
                        user-class-verification:
                            binding_keys: ['user-class-verification']
            user_updated_transport:
                serializer: messenger.transport.symfony_serializer
                dsn: '%env(USER_UPDATED_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: student_update
                        type: fanout
                    queues:
                        student_update_class: ~


        routing:
            'App\Message\UserClassVerificationMessage': user_class_verification_transport
            'App\Message\ResponseSagaItemMessage': response_saga_item_transport
            'App\Message\UserUpdatedMessage': user_updated_transport
