framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            exam_registration_transport:
                serializer: messenger.transport.symfony_serializer
                dsn: '%env(EXAM_REGISTRATION_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: exam-registration
                        type: direct
                        default_publish_routing_key: exam-registration
                    queues:
                        exam-registration:
                            binding_keys: [ 'exam-registration' ]
            response_saga_item_transport:
                serializer: messenger.transport.symfony_serializer
                dsn: '%env(RESPONSE_SAGA_ITEM_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: response-saga-item
                        type: direct
                        default_publish_routing_key: response-saga-item
                    queues:
                        response-saga-item:
                            binding_keys: [ 'response-saga-item' ]

        routing:
            'App\Message\ExamRegistrationMessage': exam_registration_transport
            'App\Message\ResponseSagaItemMessage': response_saga_item_transport
